# Generated by Django 3.1.2 on 2020-10-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201004_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_pat', models.CharField(max_length=20)),
                ('apellido_mat', models.CharField(max_length=20)),
                ('edad', models.PositiveIntegerField()),
            ],
        ),
    ]
